version: '3'

services:
  mysql_server:
    image: mysql:latest
    container_name: mysql_server
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-app:latest
    container_name: node-app
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      mysql_server:
        condition: service_healthy
    environment:
      - NODE_ENV=production

volumes:
  mysql_data:
