version: '3'

networks:
  node_api_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

services:
  mysql_server:
    image: mysql:latest
    container_name: mysql_server
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      node_api_network:
        ipv4_address: 172.19.0.3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-app:latest
    container_name: node-app
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      mysql_server:
        condition: service_healthy
    environment:
      - NODE_ENV=production
    networks:
      node_api_network:
        ipv4_address: 172.19.0.5

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      # - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - app
    networks:
      node_api_network:
        ipv4_address: 172.19.0.4

volumes:
  mysql_data:


